"""Evidence-pinned model profiles built on the framework-independent core."""

from comfyui_sigmax.profiles.krea2_common import (
    DimensionAlignmentMode,
    DimensionPolicy,
    EvidenceReference,
    GuidanceConvention,
    Krea2ImageGeometry,
    ShiftParameterization,
    resolve_krea2_image_geometry,
)
from comfyui_sigmax.profiles.krea2_raw import (
    KREA2_RAW_DIFFUSERS_REFERENCE_28,
    KREA2_RAW_OFFICIAL_FULL_52,
    KREA2_RAW_PROFILE,
    ExtrapolationPolicy,
    Krea2RawProfile,
    Krea2RawRecipe,
    Krea2RawShiftDerivation,
    ResolutionShiftMode,
    ResolutionShiftPolicy,
    build_krea2_raw_schedule,
    calculate_krea2_raw_mu,
    derive_krea2_raw_shift,
)
from comfyui_sigmax.profiles.krea2_turbo import (
    KREA2_TURBO_PROFILE,
    Krea2TurboProfile,
    build_krea2_turbo_schedule,
)
from comfyui_sigmax.profiles.krea2_variant import (
    KREA2_RAW_OFFICIAL_SHA256,
    KREA2_TURBO_OFFICIAL_SHA256,
    Krea2Variant,
    Krea2VariantConfidence,
    Krea2VariantEvidence,
    Krea2VariantEvidenceSource,
    Krea2VariantResolution,
    Krea2VariantResolutionError,
    Krea2VariantResolutionStatus,
    collect_krea2_variant_evidence,
    resolve_krea2_variant,
)

__all__ = [
    "KREA2_RAW_DIFFUSERS_REFERENCE_28",
    "KREA2_RAW_OFFICIAL_FULL_52",
    "KREA2_RAW_OFFICIAL_SHA256",
    "KREA2_RAW_PROFILE",
    "KREA2_TURBO_OFFICIAL_SHA256",
    "KREA2_TURBO_PROFILE",
    "DimensionAlignmentMode",
    "DimensionPolicy",
    "EvidenceReference",
    "ExtrapolationPolicy",
    "GuidanceConvention",
    "Krea2ImageGeometry",
    "Krea2RawProfile",
    "Krea2RawRecipe",
    "Krea2RawShiftDerivation",
    "Krea2TurboProfile",
    "Krea2Variant",
    "Krea2VariantConfidence",
    "Krea2VariantEvidence",
    "Krea2VariantEvidenceSource",
    "Krea2VariantResolution",
    "Krea2VariantResolutionError",
    "Krea2VariantResolutionStatus",
    "ResolutionShiftMode",
    "ResolutionShiftPolicy",
    "ShiftParameterization",
    "build_krea2_raw_schedule",
    "build_krea2_turbo_schedule",
    "calculate_krea2_raw_mu",
    "collect_krea2_variant_evidence",
    "derive_krea2_raw_shift",
    "resolve_krea2_image_geometry",
    "resolve_krea2_variant",
]
