"""Dependency-free framework adapter boundaries."""

from comfyui_sigmax.adapters.comfyui import (
    COMFYUI_ADAPTER_SCHEMA_ID,
    COMFYUI_ADAPTER_SCHEMA_VERSION,
    COMFYUI_HOST_WINDOW,
    ComfyAdapterCompatibilityError,
    ComfyAdapterEvidence,
    ComfyAdapterReason,
    ComfyApiLifecycle,
    ComfyApiProbe,
    ComfyHostWindow,
    ComfyNodeDefinition,
    ComfyNodeInput,
    ComfyNodeOutput,
    ComfyNodeSchemaForm,
    adapt_comfyui_host,
    adapt_krea2_model_evidence,
    normalize_node_definition_v2,
    normalize_object_info,
    probe_comfy_api,
    require_stable_numbered_api,
)

__all__ = [
    "COMFYUI_ADAPTER_SCHEMA_ID",
    "COMFYUI_ADAPTER_SCHEMA_VERSION",
    "COMFYUI_HOST_WINDOW",
    "ComfyAdapterCompatibilityError",
    "ComfyAdapterEvidence",
    "ComfyAdapterReason",
    "ComfyApiLifecycle",
    "ComfyApiProbe",
    "ComfyHostWindow",
    "ComfyNodeDefinition",
    "ComfyNodeInput",
    "ComfyNodeOutput",
    "ComfyNodeSchemaForm",
    "adapt_comfyui_host",
    "adapt_krea2_model_evidence",
    "normalize_node_definition_v2",
    "normalize_object_info",
    "probe_comfy_api",
    "require_stable_numbered_api",
]
