name: Publish to Comfy registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"

permissions:
  contents: read

concurrency:
  group: comfy-registry-publish
  cancel-in-progress: false

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    if: >-
      github.repository == 'rookiestar28/ComfyUI-Sigmax' &&
      github.event.repository.fork == false
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pragma: allowlist secret
        with:
          persist-credentials: false
      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@d2366e7abb6ab16f3bb03e3520ae25c8cf749bc9 # pragma: allowlist secret
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
          skip_checkout: true
